import { SessionProvider } from 'next-auth/react'
import { Main, globalStyles } from '@/styles/globals'
import type { AppProps } from 'next/app'
import { Nunito_Sans } from 'next/font/google'
import { QueryClientProvider } from 'react-query'
import { queryClient } from '@/lib/react-query'

import '../lib/dayjs'
import DefaultLayout from '@/layouts/DefaultLayout'
import Head from 'next/head'

const nunito = Nunito_Sans({
  subsets: [],
  weight: ['400', '700'],
})

globalStyles()

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <SessionProvider session={session}>
        <Head>
          <title>BookWise</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.svg' />
        </Head>
        <Main className={nunito.className}>
          <DefaultLayout>
            <div style={{ maxWidth: 996 }}>
              <Component {...pageProps} />
            </div>
          </DefaultLayout>
        </Main>
      </SessionProvider>
    </QueryClientProvider>
  )
}
