import Head from 'next/head';
import { globalStyles } from '@/styles/globals';
import Home from './home';

globalStyles();

export default function Page() {
  return (
    <>
      <Head>
        <title>BookWise</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Home />
    </>
  );
}
